# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build

on:
  push:
    branches:
    - master
    
defaults:
  run:
    shell: bash
    working-directory: src/366x366

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 14         
      - name: Delete package.json 
        run: rm -f src/366x366/package.json
      - name: Move Pre-Release package.json 
        run: rm -f mv src/366x366/pr-package.json src/366x366/package.json
      - name: install
        run: npm install      
      - name: build
        run: npx fitbit-build
      - name: Upload fba
        uses: actions/upload-artifact@v3
        with:
          name: pr-fitbit-overview
          path: src/366x366/build/app.fba         
      - name: Delete package.json 
        run: rm -f src/366x366/package.json
      - name: Move Release package.json 
        run: rm -f mv src/366x366/real-package.json src/366x366/package.json
      - name: install
        run: npm install      
      - name: build
        run: npx fitbit-build
      - name: Upload fba
        uses: actions/upload-artifact@v3
        with:
          name: fitbit-overview
          path: src/366x366/build/app.fba
